prometheus:
  prometheusSpec:
    podMonitorSelector:
      matchLabels: null
    probeSelector:
      matchLabels: null
    ruleSelector:
      matchLabels: null
    scrapeConfigSelector:
      matchLabels: null
    serviceMonitorSelector:
      matchLabels: null

  additionalServiceMonitors:
    - name: flask-app-monitor
      selector:
        matchLabels:
          app: api
      namespaceSelector:
        matchNames:
          - hello-kube
      endpoints:
        - path: /metrics
          interval: 15s

thanosRuler:
  thanosRulerSpec:
    ruleSelector:
      matchLabels: null
